# Generated by Django 2.2.10 on 2020-03-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200302_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anotherfinal',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='final',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='test57435',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
