# Generated by Django 2.2.10 on 2020-03-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
